---
- hosts: all 
  become: yes 
  tasks: 
  - name: createa file 
    lineinfile:
      path: /mnt/mysql_backups/database_list.txt
      line: dev,test,qa,prod
      create: yes
  - name: Archive FIle
    archive: 
      path: /mnt/mysql_backups/database_list.txt
      dest:  /mnt/mysql_backups/archive.gz
      format: gz

