---
- hosts: all 
  become: yes 
  tasks: 
  - name: vm swappines above 2048
    sysctl: 
       name: vm.swappiness
       value: '5'
       state: present
       reload: yes
    when: 
    - ansible_memory_mb.real.total > 2048
  - name: show error
    debug: 
       msg: "Server memory less than 2048MB server memory is {{ansible_memory_mb.real.total }}MB"
    when:
    - ansible_memory_mb.real.total < 2048
